Bypass grid-level water mass check when fates hydro is active
ESCOMP/CTSM pull request #1334
Opened 2021-04-13 17:04 UTC by rgknox

### Description of changes

With changes forthcoming in FATES PR: https://github.com/NGEET/fates/pull/727 , 

Column-scale water balance checks with FATES-HYDRO are passing with consistency, including scenarios where plants are allowed to by dynamic (grow, recruit, die and non-mortal turnover).  However, we are still failing a grid-level mass balance check.

See issue: #1314 

This PR is a temporary fix, that bypasses grid-scale water mass checks only for fates-hydro runs.  Since column level checks pass, the expectation is that there is a bug on the upscaling from column to grid that is presently unknown. However, this PR will allow hydro tests to pass which will prevent further regressions.

### Specific notes

CTSM Issues Fixed (include github issue #):  Does not fix, but addresses #1314 partially.

Are answers expected to change (and if so in what way)?  Answers should go from no-answers, to has-answers for fates-hydro. Should not impact other answers.

Any User Interface Changes (namelist or namelist defaults changes)?  No

Testing performed, if any:

TBD

(List what testing you did to show your changes worked as expected)
(This can be manual testing or running of the different test suites)
(Documentation on system testing is here: https://github.com/ESCOMP/ctsm/wiki/System-Testing-Guide)
(aux_clm on cheyenne for intel/gnu and izumi for intel/gnu/nag/pgi is the standard for tags on master)

**NOTE: Be sure to check your coding style against the standard
(https://github.com/ESCOMP/ctsm/wiki/CTSM-coding-guidelines) and review
the list of common problems to watch out for
(https://github.com/ESCOMP/CTSM/wiki/List-of-common-problems).**

2021-04-13 18:03 UTC, billsacks requested changes
This is fine. Can you just please add a comment like this above the line of code that you changed:

```Fortran
  ! BUG(wjs, 2021-04-13, ESCOMP/CTSM#1314) Temporarily bypassing gridcell-level check with use_fates_planthydro until issue 1314 is resolved
```

(So we have some explanation that we can refer back to in case this temporary code stays in place for a while.)

2021-04-13 18:11 UTC, ekluzek approved these changes
I agree with @billsacks just make sure you have some comments in the code that document about this. I'd even suggest adding a note to the Fates Hydro test that notes that grid-level mass check is turned off. It's really easy to forget these temporary work arounds are put in place, and they often last much longer than you'd like.

2021-04-13 18:33 UTC, rgknox commented
will do, great suggestions!

2021-04-13 20:05 UTC, billsacks approved these changes
Great, thanks!

2021-04-13 21:40 UTC, rgknox commented
fyi, I'm testing out some changes in this PR to hopefully address:
https://github.com/ESCOMP/CTSM/issues/510

2021-04-15 16:54 UTC, billsacks commented on src/biogeophys/WaterDiagnosticType.F90
> +    call restartvar(ncid=ncid, flag=flag, &
- [ ] Please put this in a fates_hydro conditional

2021-04-15 17:42 UTC, rgknox commented
@billsacks , updated with conditional on the restart

2021-04-15 17:48 UTC, billsacks commented
Thanks @rgknox . I'll bring this into my upcoming tag.

Just FYI for the future: we prefer if the person who creates a check box be the one to check it off (see https://github.com/ESCOMP/CTSM/wiki/Pull-request-review-workflow). Not at all a big deal here where I just had one, but for big reviews, it helps us control-freak reviewers be able to create check lists of things we want done and then be able to verify that what we've asked was actually done.

2021-04-15 19:55 UTC, rgknox commented
I agree to not push your buttons @billsacks

2021-04-20 17:13 UTC, merged