Standardize time metadata
ESCOMP/CTSM pull request #2052
Opened 2023-07-11 21:19 UTC by samsrabin

### Description of changes
Standardizes a dimension name of output variable `time_bounds`, as well as attributes for that plus `mcdate`, `mcsec`, `mdcur`, and `mscur`.

### Specific notes

Contributors other than yourself, if any: @billsacks, @ekluzek 

CTSM Issues Fixed: #1693

Are answers expected to change (and if so in what way)? **No.**

Any User Interface Changes (namelist or namelist defaults changes)? **No.**

Testing performed, if any: An arbitrarily-chosen test, `SMS_D_Ld3.f10_f10_mg37.I2000Clm50BgcCru.cheyenne_gnu.clm-default.C.0711-150307ch`, **passed bit-for-bit** against tag `ctsm5.1.dev130`.

2023-07-11 21:22 UTC, samsrabin commented
Marked as blocked:dependency because, at the moment, `Externals.cfg` points to branches of my personal MOSART (issue ESCOMP/MOSART#53) and RTM (issue ESCOMP/RTM#31) forks that contain the same changes. I haven't yet submitted those as pull requests, because I first wanted to see if any more testing is requested.

2023-08-31 15:58 UTC, samsrabin commented
From CTSM software engineering meeting today: This doesn't need to wait on other time-related PRs. It can come in as soon as the relevant externals are updated (and Externals.cfg here is changed to point to them).

2024-10-17 15:50 UTC, wwieder commented
It seems like this could come onto b4b-dev without breaking anything and wouldn't have to be coordinated with RTM and MOSART tags (although it would make inconsistencies between the component outputs).  On net, however, this would mean having to make another tag to update submodules.  Maybe we just wait on this for now.

2024-11-20 00:14 UTC, slevis-lmwg commented
Testing includes all three "history" PRs (this one, #2084, #2838) and their mosart/rtm counterparts:

derecho
PASS build-namelist_test.pl
PASS python testing
```
IN PROG ./run_sys_tests -s rtm -c rtm1_0_83-ctsm5.3.012_zerothtstep -g rtm1_0_83-ctsm5.3.012_zeroth+stdize_tmeta
IN PROG ./run_sys_tests -s mosart -c mosart1.1.05-ctsm5.3.012_zerothtstep -g mosart1.1.05-ctsm5.3.012_zeroth+stdize_tmeta
IN PROG ./run_sys_tests -s aux_clm -c ctsm5.3.012_zerothtstep -g ctsm5.3.012_zeroth+stdize_tmeta
```

izumi
```
IN PROG ./run_sys_tests -s mosart -c mosart1.1.05_ctsm5.3.012_zerothtstep -g mosart1.1.05_ctsm5.3.012_zeroth+stdize_tmeta
IN PROG ./run_sys_tests -s aux_clm -c ctsm5.3.012_zerothtstep -g ctsm5.3.012_zeroth+stdize_tmeta
```

2024-11-22 03:13 UTC, slevis-lmwg commented
I updated my copy of this branch and its rtm/mosart counterparts with the changes from this commit
https://github.com/ESCOMP/CTSM/pull/2838/commits/eeedbc6ae95373cbd1f27359f54de7693409326d
and submitted
`./create_test RXCROPMATURITYSKIPGEN_Ld1097.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-cropMonthOutput`
to see if we need to worry about the failure that I got in this test today in #2838.

Also
`./create_test ERI_D.ne30pg3_t232.I1850Clm60BgcCropG.derecho_intel.clm-clm60cam7LndTuningModeLDust -c /glade/campaign/cgd/tss/ctsm_baselines/ctsm5.3.012`
to see if we need to worry about the restart diffs that I got in the zerothtstep branch. Other diffs are expected in this comparison, same as in the zerothtstep comparison I think.

2024-11-22 17:41 UTC, samsrabin commented
Okay, I'll look into it.

2025-01-10 19:29 UTC, slevis-lmwg commented
BEFORE MAKING THE RTM/MOSART TAGS FOR THIS PR...

TODOs from #2838:
- [ ] Make the same or equivalent change as https://github.com/ESCOMP/CTSM/pull/2838/commits/eeedbc6ae95373cbd1f27359f54de7693409326d to the corresponding rtm/mosart files.
- [ ] Resolve mosart/cpl BASELINE DIFFs discussed initially [here](https://github.com/ESCOMP/CTSM/pull/2838#issuecomment-2477608383)
 by replacing the if-statement in commit [692d183](https://github.com/ESCOMP/MOSART/pull/70/commits/692d1839489d6979c1a241e0f638189186405cfc) with a comment, as explained in https://github.com/ESCOMP/MOSART/issues/103#issuecomment-2479679014.

2025-01-11 00:40 UTC, ekluzek requested changes
From a skim of the changes I don't see issues to comment on. The changes of ctsm5.3.018 and ctsm5.3.019 are included here, so a lot of differences will go away and it will be easier to see what's going on.

@samsrabin since you did this work, it might be good have you go over some of it with @slevis-lmwg and I. I know it was forever ago and you don't remember a lot of it, but it'll probably work fine to have all of us look at it together. So let's tentatively plan on doing that next week if possible.

At this point the python unit testing and the RXCROP tests should all work and we should make sure they do. This could be to just run ctsm_sci as mentioned just below.

If this is the tag that we are going to mark as the ctsm5.3 release tag, we should also run fates and ctsm_sci test lists. And we should make sure b4b-dev has come in by this tag. And we should make sure the WhatsNewInCtsm5.3 file is updated with the latest we have for the document that talks about it.

2025-01-11 00:40 UTC, ekluzek commented on .gitmodules
> +fxtag = rtm1_0_83
The rtm and mosart tags will be the new rtm1_0_85 and mosart1.1.08

2025-01-11 00:40 UTC, ekluzek commented on doc/ChangeLog
> +Tag name: ctsm5.3.014
This ChangeLog stuff can just be removed as part of the update to ctsm5.3.019.

2025-01-13 20:35 UTC, ekluzek commented
The ERI test passes in ctsm5.3.017, so there's something in here causing trouble.

2025-01-14 23:30 UTC, slevis-lmwg commented on doc/ChangeLog
> +Tag name: ctsm5.3.014
Yes, this disappeared as soon as I updated to ctsm5.3.019.

2025-01-15 02:01 UTC, slevis-lmwg commented
Note to self: Consider initiating further testing, but perform final testing after updating to ctsm5.3.020.

2025-01-16 17:20 UTC, samsrabin commented
- [ ] Finalize [release notes](https://docs.google.com/document/d/12KS5eU6gIaicZ4hJhgZWmys8fLLl5IkxwC_Pi76FuHw/edit?tab=t.0)

2025-01-16 19:26 UTC, slevis-lmwg commented
Questions:
Given that we will mark this tag as the release tag for ctsm5.3:
- Would it make sense for us to include the one-line ccs_config update to enable f09_t232? 
- Is it complicated to make a new ccs_config tag? I doubt that I have permission. 
- Or is there a way around making a new ccs_config tag?
- Or should we wait for the fix to come in later?

2025-01-16 21:58 UTC, wwieder commented
@slevis-lmwg this is a good question. If the ccs_config updates can come in quickly, I'm supportive of wrapping the external update into this tag.  

If this will take long, however, I'm wary of scope creep and somewhat less worried about how we're defining there minor version tags (especially since we expect a 5.4 tag to be made in the next few months).  I'm also hesitant to hold up our upcoming tags, because it seemed like there are several FATES tags that are pretty critically and backed up against 5.3.021.

2025-01-16 23:28 UTC, slevis-lmwg commented
> @slevis-lmwg this is a good question. If the ccs_config updates can come in quickly, I'm supportive of wrapping the external update into this tag.
> 
> If this will take long, however, I'm wary of scope creep and somewhat less worried about how we're defining there minor version tags (especially since we expect a 5.4 tag to be made in the next few months). I'm also hesitant to hold up our upcoming tags, because it seemed like there are several FATES tags that are pretty critically and backed up against 5.3.021.

Yay, I see that this was addressed here:
https://github.com/ESMCI/ccs_config_cesm/pull/205
Thank you @fischer-ncar and @wwieder

2025-01-16 23:39 UTC, ekluzek commented
Nice that we have a tag for the simple fix needed. So you should just include that here.

I will say that I'm supportive of this NOT having everything clean even for this tag being a development release tag. At least in this case when running with MOM masks in stand-alone CTSM is still considered "experimental". I know it shouldn't be thought of that way, but until it's standard practice -- it's experimental. The fact that it was broken the first time we tried it -- just underscores how "experimental" it really is right now.

2025-01-16 23:45 UTC, ekluzek commented
And @slevis-lmwg just to be explicit on your questions:

> * Is it complicated to make a new ccs_config tag? I doubt that I have permission.

It's not complicated, once a ccs_config PR is merged it automatically creates a tag for it.

BUT what is critical here is to have done enough testing with it that it doesn't break something in CESM. In this case it was easy to approve because it was so isolated to handling a grid that wasn't working. So your testing was sufficient.

@jedwards4b and @fischer-ncar are the main contributors to ccs_config from CSEG. There's a few others too though.

> * Or is there a way around making a new ccs_config tag?

Not, really other than maybe doing a branch tag, but I don't think we should do that most of the time if ever.

2025-01-16 23:47 UTC, slevis-lmwg commented
Also there's a possible caveat to updating to the latest ccs_config:
ctsm5.3.020 is updating to ccs_config_cesm1.0.16. Beyond that I see tags upto ccs_config_cesm1.0.19, so the f09_t232 fix is not the only thing that we'd be getting by updating...

2025-01-16 23:51 UTC, ekluzek commented
It looks like those changes in ccs_config tags *should* be benign. But, they also haven't gone through CESM testing, so I'd treat them a little suspect. I suggest you try it with it updated, but if it causes any problems -- back that update out.

2025-01-17 20:19 UTC, slevis-lmwg commented
I started tests on derecho:
```
PASS ./build-namelist_test.pl
PASS black and lint, though the latter gave 2 warnings
PASS ./run_ctsm_py_tests
./run_sys_tests -s rtm -c rtm1_0_86-ctsm5.3.019 -g rtm1_0_86-ctsm5.3.020
./run_sys_tests -s mosart -c mosart1.1.08-ctsm5.3.019 -g mosart1.1.08-ctsm5.3.020
./run_sys_tests -s aux_clm -c ctsm5.3.020 -g ctsm5.3.021
./run_sys_tests -s ctsm_sci -c ctsm_sci-ctsm5.3.016 -g ctsm_sci-ctsm5.3.021
./run_sys_tests -s fates -c fates-sci.1.80.9_api.37.0.0-ctsm5.3.018 -g fates-sci.1.80.9_api.37.0.0-ctsm5.3.021
```
TODO: Rename the 020 suffixes above to 021, when the baselines have been generated.

Izumi
```
./run_sys_tests -s mosart -c mosart1.1.08-ctsm5.3.019 -g mosart1.1.08-ctsm5.3.021
./run_sys_tests -s aux_clm -c ctsm5.3.020 -g ctsm5.3.021
./run_sys_tests -s fates -c fates-sci.1.80.4_api.37.0.0-ctsm5.3.014 -g fates-sci.1.80.4_api.37.0.0-ctsm5.3.021
```

2025-01-17 20:32 UTC, slevis-lmwg commented
I rushed to start testing and didn't first update to ccs_config_cesm1.0.20.
But... maybe that's better, so as to confirm first that everything works without that update.

2025-01-17 22:49 UTC, slevis-lmwg commented
@samsrabin I'm afraid the RXCROP... test fails again in the latest aux_clm. You can look here:
/glade/derecho/scratch/slevis/tests_0117-125438de/RXCROPMATURITYSKIPGEN_Ld1097.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-cropMonthOutput.GC.0117-125438de_int

2025-01-18 01:36 UTC, slevis-lmwg commented
UPDATE
I interpret `git diff d89c86e` to suggest that we didn't miss anything, and that it's all there as it was before the latest updates. I think this means that the RXCROP... tests fail due to something new in the updates. @samsrabin I'm coming up with two options:
1) "time" is now the middle of "time_bounds"
2) the elimination of the 0th time step

I'm happy to help troubleshoot this next week if you like.

2025-01-21 23:46 UTC, slevis-lmwg commented
As a sanity check, I checked out 08753cd and submitted
`./create_test RXCROPMATURITYSKIPGEN_Ld1097.f10_f10_mg37.IHistClm60BgcCrop.derecho_intel.clm-cropMonthOutput`
in case there was a version when this test passed.

2025-01-22 19:31 UTC, slevis-lmwg commented
@samsrabin I have determined that the 3-line change in 08753cd breaks the RXCROP tests. Could we discuss how to resolve or do you prefer to investigate yourself?

2025-01-23 01:26 UTC, slevis-lmwg commented
From meeting with @ekluzek, still TODO for Sam L:
- [ ] Update to ccs_config_cesm1.0.20 and rerun testing on derecho, comparing against the baselines that I generated last.
- [ ] Test mksurfdata_esmf
- [ ] Replicate https://github.com/NCAR/LMWG_dev/issues/70 (or 69 or 68) using this new release tag and make sure I get the same namelists, though expect answers to change due to dust
- [ ] In [What's new in CTSM 5.3](https://docs.google.com/document/d/12KS5eU6gIaicZ4hJhgZWmys8fLLl5IkxwC_Pi76FuHw/edit?tab=t.0), 
  - [ ] ADD INFO ABOUT the HISTORY CHANGES
  - [ ] ADD PR links to "soil mksurfdata_esmf bug" and other paragraphs

2025-01-23 01:59 UTC, slevis-lmwg commented
Updated to ccs_config_cesm1.0.20 and started testing on derecho
```
IN PROG ./run_sys_tests -s mosart --skip-generate -c mosart1.1.08-ctsm5.3.021
IN PROG ./run_sys_tests -s rtm --skip-generate -c rtm1_0_86-ctsm5.3.021
FAIL ./run_sys_tests -s ctsm_sci --skip-generate -c ctsm_sci-ctsm5.3.021
FAIL ./run_sys_tests -s fates --skip-generate -c fates-sci.1.80.4_api.37.0.0-ctsm5.3.021
FAIL ./run_sys_tests -s aux_clm --skip-generate -c ctsm5.3.021
```
tests_0122-184811de
tests_0122-184944de
The 3 FAILs are non starters with Permission denied in ctsm_pylib and python errors outside of ctsm_pylib.

Bisect to identify the ccs_config tag responsible for this? Update to ccs_config_cesm1.0.21?

2025-01-23 18:47 UTC, slevis-lmwg commented
The following PASS in aux_clm despite issue #2310. I imagine they may still fail once in a while, but I do not know...

@samsrabin @ekluzek @adrifoster do you want me to remove these from EXPECTED? I don't think we covered these in this morning's meeting, did we?
```
    PASS SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Bgc.derecho_gnu.clm-default--clm-NEON-HARV SHAREDLIB_BUILD time=13 (UNEXPECTED: expected FAIL)
    PASS SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Bgc.derecho_gnu.clm-NEON-MOAB--clm-PRISM SHAREDLIB_BUILD time=11 (UNEXPECTED: expected FAIL)
    PASS SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Bgc.derecho_gnu.clm-NEON-MOAB--clm-PRISM RUN time=91 (UNEXPECTED: expected FAIL)
    PASS SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Fates.derecho_gnu.clm-FatesPRISM--clm-NEON-FATES-YELL SHAREDLIB_BUILD time=9 (UNEXPECTED: expected FAIL)
    PASS SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Fates.derecho_gnu.clm-FatesPRISM--clm-NEON-FATES-YELL RUN time=102 (UNEXPECTED: expected FAIL)
    PASS SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Fates.derecho_intel.clm-FatesFireLightningPopDens--clm-NEON-FATES-NIWO SHAREDLIB_BUILD time=10 (UNEXPECTED: expected FAIL)
```

The following PASS in fates despite issue #2310. Same question.
```
    PASS SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Fates.derecho_gnu.clm-FatesPRISM--clm-NEON-FATES-YELL SHAREDLIB_BUILD time=15 (UNEXPECTED: expected FAIL)
    PASS SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Fates.derecho_gnu.clm-FatesPRISM--clm-NEON-FATES-YELL RUN time=99 (UNEXPECTED: expected FAIL)
    PASS SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Fates.derecho_intel.clm-FatesFireLightningPopDens--clm-NEON-FATES-NIWO SHAREDLIB_BUILD time=102 (UNEXPECTED: expected FAIL)
```

2025-01-23 20:22 UTC, samsrabin commented
The NEON ones _sometimes_ pass—it all depends on how cooperative the data server is being. So they should stay as expected fail.

2025-01-23 22:41 UTC, ekluzek commented
@slevis-lmwg yes leave them as expected fails in case they do fail for someone because of network/server issues. It's a signal to them that they can move on. The longer term solution that @adrifoster is endorsing and I agree -- I added to the new issue #2942. Once we get that going we'd be able to remove the expected fail.

2025-01-25 01:45 UTC, samsrabin commented
RXCROPMATURITY tests are now working!

2025-01-25 17:54 UTC, slevis-lmwg commented
> RXCROPMATURITY tests are now working!

@samsrabin thank you! Could you tell me the vetted baselines to copy for these tests?

2025-01-29 07:19 UTC, ekluzek commented
@slevis-lmwg and went over namelist differences as outlined in the Minor version update protocol wiki page with things like:

``` shell
cd bld/unit_testers
./compare_namelists -b $SCRATCH/ctsm5.3.007/bld/unit_testers/ -pa clm6_0 -pb clm6_0 | & grep -v cnfun_inparm | grep -v upplim_destruct_metamorph | grep -v maximum_leaf_wetted_fraction | grep -v interception_fraction | grep -v paramfile | grep -v clm_canopyhydrology_inparm | grep -v DIFF | grep -v "No case id data available" | grep -v "Namelist diff" | grep -v jmaxb1 | grep -v clm_inparm
./cmp_baseline_lnd_in_files ctsm5.3.007 ctsm5.3.021 | & grep -v cnfun_inparm | grep -v upplim_destruct_metamorph | grep -v maximum_leaf_wetted_fraction | grep -v interception_fraction | grep -v paramfile | grep -v clm_canopyhydrology_inparm | grep -v DIFF | grep -v "No case id data available" | grep -v "Namelist diff" | grep -v jmaxb1 | grep -v clm_inparm | grep -v "hist_"
```

which highlighted just the namelist differences that were unexpected. We had to do it a few times to figure out what to remove with grep, so unexpected things would pop out. Doing the above helped highlight a few things that we had forgotten about, but realized were expected. And it also helped to ensure we have confidence that the namelist settings are correct and something didn't get changed in a tag to mess them up. This gives us confidence that this tag will be a good starting point for scientists who need to do simulations with a stable version to use with their science. As such it will be marked as a development release tag.

2025-01-29 15:33 UTC, ekluzek commented
@slevis-lmwg I compared the namelists for ctsm_sci ctsm5.3.0 and ctsm5.3.021 baselines and saw the same things that popped out when we looked together. So the completes the namelist validation checking for this tag.

@slevis-lmwg and I also didn't think there was any additional code review that needed to be done by anyone for this. Tags that came in were reviewed and all reasonable ones (in terms of length). And we didn't see anything that seemed likely where a later tag might have messed something up from an earlier one.

2025-01-29 23:31 UTC, ekluzek approved these changes

2025-01-30 00:08 UTC, merged