Fix "Assign to project" action (?)
ESCOMP/CTSM pull request #2342
Opened 2024-01-31 21:57 UTC by samsrabin

### Description of changes
Removes backticks from the YAML file that were causing syntax errors

### Specific notes

**Contributors other than yourself, if any:** @mvdebolskiy, @ekluzek 

**CTSM Issues Fixed (include github issue #):** None

**Are answers expected to change (and if so in what way)?** No

**Any User Interface Changes (namelist or namelist defaults changes)?** No

**Testing performed, if any:** None

2024-02-01 07:07 UTC, ekluzek requested changes
You also need to remove the : after priority: on line 16.

We should just approve this and send it to master without worrying about a tag.

2024-02-01 14:56 UTC, wwieder commented
seems good, Erik. I don't think this needs a tag.

2024-02-01 15:33 UTC, merged

2024-02-02 12:41 UTC, mvdebolskiy commented
Can you rerun `[Merge tag 'ctsm5.1.dev166' into CESM3_dev](https://github.com/ESCOMP/CTSM/actions/runs/7750813536)` action to see if it doesn't fail?

2024-02-02 15:43 UTC, samsrabin commented
Hmm. Not sure how I would do that.

2024-02-02 16:43 UTC, mvdebolskiy commented
Oh, you can't apparently. https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs