MIMICS updates, WIP
ESCOMP/CTSM pull request #2365
Opened 2024-02-14 23:30 UTC by wwieder

### Description of changes
code and parameter changes to address #2361

### Specific notes
removes NPP control on turnover
fixes density dependent control on turnover
adds litterfall fluxes that bypass litter pools, directly contributing to SOM

**Contributors other than yourself, if any:**
@slevis-lmwg 

**CTSM Issues Fixed (include github issue #):**
#2361

**Are answers expected to change (and if so in what way)?**
Soil C stocks will change with these code and parameter updates

**Any User Interface Changes (namelist or namelist defaults changes)?**
/glade/u/home/wwieder/scratch/mimics_NEON/modified parameter file available ctsm51_params.c240207b_v1.3_t1.5_b1.5.nc 

**Testing performed, if any:**
scientific testing in single point cases is ongoing

2024-02-14 23:31 UTC, wwieder commented on cime_config/usermods_dirs/NEON/defaults/shell_commands
Changes to user_mods don't need to be included in this PR.

2024-02-14 23:43 UTC, wwieder commented
@slevis-lmwg the parameter files listed above has `mimics_fi` added to it.  Let me know if this looks OK to you.
Note, this also makes changes to several other MIMICS parameters (mimics_vint, mimics_densdep, & mimics_tau_mod)

2024-03-16 01:15 UTC, slevis-lmwg commented
I checked out this branch, added the code that we discussed, and pointed to the above params file. The model builds and runs.

I tried to push back to the branch, but I do not have permissions.

The files to copy to your /SourceMods are:
```
biogeochem/CNCStateUpdate1Mod.F90
biogeochem/CNNStateUpdate1Mod.F90
main/clm_varpar.F90
main/pftconMod.F90
soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90
```

2024-03-16 02:32 UTC, wwieder commented
Thanks, Sam. Can you point me to the directory where your files are?

2024-03-16 15:20 UTC, slevis-lmwg commented
Sorry for the omission! I updated the post with the full file paths now.

2024-03-18 12:50 UTC, wwieder commented
That was a quick Friday afternoon!  Thanks.

You can teach me how to grant permissions at some point, but I'll kick off a few runs with these code modifications and see how they look next week.

2024-09-09 14:08 UTC, wwieder commented
also fixes #2248, by adding the density dependent microbial turnover (beta) 

@elisacw, and @mvdebolskiy I've merged this PR up to the latest tag (ctsm5.2.028).  I'll also point to an updated parameter file that can be found here.
/glade/derecho/scratch/wwieder/neon_AK/mods/ctsm60_params_vint1.3_taumod1.5_beta1.5.c240822.nc

2024-09-09 14:19 UTC, mvdebolskiy commented
@elisacw, can you make an updated parameterfile with mimicsplus params out of the one Will pointed to?

2025-02-28 20:53 UTC, slevis-lmwg commented
From conversation @wwieder @slevis-lmwg:

Add new parameters to paramfile in prep. for #1654 
Move them from src/biogeochem/CNVegNitrogenStateType.F90
```
co2_base = 310._r8  ! units ppmv
cn_slope = 0._r8
```
to paramfile with these names
leafcn_co2_base
leafcn_co2_slope

2025-03-12 19:44 UTC, slevis-lmwg commented on python/ctsm/subset_data.py
> +    dir_input_datm = os.path.join(TRENDYdir, defaults.get(datm_type, "dir"))
@wwieder 
in finishing this PR, would you mind if I reversed the changes in subset_data and default_data, since they are coming in with #2956? Currently #2956 is next in line in the Upcoming Tags.

2025-03-12 19:47 UTC, slevis-lmwg commented on cime_config/usermods_dirs/NEON/defaults/shell_commands
Addressed with https://github.com/ESCOMP/CTSM/pull/2365/commits/9a8ba0e2d9e68ff04769df35236700ab779f849d so resolving.

2025-03-12 19:56 UTC, wwieder commented on python/ctsm/subset_data.py
> +    dir_input_datm = os.path.join(TRENDYdir, defaults.get(datm_type, "dir"))
Yes please do, these modifications to subset data are not required for the MIMICS work that should be the focus of the PR.  I was lazy and did them on the same branch and didn't back them out of the merge.

2025-03-12 20:27 UTC, slevis-lmwg commented
- [ ] Reverse single_point...
- [ ] Update to latest paramfiles
- [ ] Run aux_clm

2025-03-12 20:27 UTC, wwieder commented on python/ctsm/site_and_regional/single_point_case.py
This file doesn't need to be changed as part of this PR, @slevis-lmwg can you back it out

2025-03-12 20:32 UTC, wwieder commented on src/main/clm_varpar.F90
parameters added and modified on the parameter files available here `/glade/derecho/scratch/wwieder/param_mods`

2025-03-13 01:24 UTC, slevis-lmwg commented
**derecho aux_clm results**
Rerunning CN30 test manually, because it also needed a new paramfile:
`./create_test SMS_Lm1.f10_f10_mg37.I1850Clm60Bgc.derecho_intel.clm-clm60_monthly_matrixcn_soilCN30 -c /glade/campaign/cgd/tss/ctsm_baselines/ctsm5.3.030`

Otherwise, ok:
```
FAIL ERS_Ld3.f10_f10_mg37.I2000Clm60Bgc.derecho_intel.clm-ciso_cwd_hr BASELINE ctsm5.3.030: DIFF
FAIL ERS_Ld3.f10_f10_mg37.I2000Clm60Bgc.derecho_intel.clm-ciso_cwd_hr--clm-matrixcnOn BASELINE ctsm5.3.030: DIFF
```
I expected the diffs in mimics cases but not in these ciso cases. However, I see (and remember discussing with @wwieder) that the most recent previous ciso params file had roundoff diffs from the rest for no reason that we could identify. The new one does not have such diffs.

2025-03-13 04:03 UTC, wwieder commented
Just remembered, was there another parameter file I needed to create for testing purposes?

2025-03-13 16:48 UTC, slevis-lmwg commented
> Just remembered, was there another parameter file I needed to create for testing purposes?

There are two (CN30 and ciso), and I went ahead and made them.

2025-03-15 00:03 UTC, slevis-lmwg requested changes
The changes seem reasonably straightforward and follow the existing code setup that we put in place for mimics a few years ago. I will approve when @wwieder checks the ChangeLog and when this PR gets in line for merging to master.

2025-03-16 01:09 UTC, wwieder commented
There are also some modifications to the default mimics parameters, but nothing that needs to be documented here

2025-03-17 16:52 UTC, slevis-lmwg approved these changes

2025-03-19 20:51 UTC, merged