Add a namelist warning when hillslope hydrology is used with initial interpolation.
ESCOMP/CTSM pull request #2703
Opened 2024-08-15 19:22 UTC by mvdebolskiy

### Description of changes

Added warning to `CLMBuildNamelist.pm` and a warning test in `build-namelist_test.pl`.

### Specific notes

The warning is added after logic for initial conditions is done.

Contributors other than yourself, if any:

CTSM Issues Fixed (include github issue #):

#1806

Are answers expected to change (and if so in what way)?

No.

Any User Interface Changes (namelist or namelist defaults changes)?

You have to run `./xmlchange --append CLM_BLDNML_OPTS=-ignore_warnings` if you want to have `use_init_interp` with `use_hillslope` both true.

Does this create a need to change or add documentation? Did you do so?

Testing performed, if any:

ran build-namelist_test.pl and tested a new case with above namelist changes

**NOTE: Be sure to check your coding style against the standard
(https://github.com/ESCOMP/ctsm/wiki/CTSM-coding-guidelines) and review
the list of common problems to watch out for
(https://github.com/ESCOMP/CTSM/wiki/List-of-common-problems).**

2024-08-22 08:17 UTC, ekluzek approved these changes
This should be rebased to b4b-dev, but otherwise this is great.

2024-08-22 15:26 UTC, samsrabin commented
Converting to draft, pending the rebase.

2024-09-16 15:26 UTC, samsrabin requested changes
This is good to go, pending your merge of mvdebolskiy/CTSM#6.

2024-09-17 15:54 UTC, samsrabin approved these changes

2024-09-17 15:54 UTC, merged