Make sure FORTRAN code properly aborts when fire-emission is asked for and it can't be provided
ESCOMP/CTSM pull request #2844
Opened 2024-10-23 06:05 UTC by ekluzek

### Description of changes

Changes in the FORTRAN code to properly abort when fire-emission is asked for it can't be provided.

To develop this a PF unit test for CNFireFactoryMod is added in.

### Specific notes

Contributors other than yourself, if any:

CTSM Issues Fixed (include github issue #):
  Fixes #2762

Are answers expected to change (and if so in what way)? No

Any User Interface Changes (namelist or namelist defaults changes)? No

Does this create a need to change or add documentation? Did you do so? No

Testing performed, if any: Currently just the PF unit tests will run regular testing when done.

2025-03-24 20:14 UTC, ekluzek commented on cime_config/config_component.xml
> +      <value compset="CAM[^_]*_CLM[^_]*BGC-CROP"  >--bgc bgc --crop --no-megan --no-drydep --no-fire_emiss</value>
Make a note about what issue this resolves.

2025-03-24 20:17 UTC, ekluzek commented on bld/CLMBuildNamelist.pm
> +                           "  DON'T use the '--fire_emis' option when '--bgc sp' is activated");
Is this doing the right thing here? Is this for both fire_emiss on and off?

2025-03-24 20:30 UTC, ekluzek commented on src/biogeochem/CNFireFactoryMod.F90
> -    character(len=*), parameter :: subname = 'create_cnfire_method'
This is implementing the modernization asked for in #1452

2025-03-24 20:39 UTC, ekluzek commented on src/biogeochem/FATESFireFactoryMod.F90
> +    end if
For now we also need to add a check for FATES turned on at all, because until we bring in changes it can't handle fire-emis with FATES.

2025-03-24 20:41 UTC, ekluzek commented on src/biogeochem/test/CNFireFactory_test/test_CNFireFactory.pf
> +      ! Create an exmpty namelist file for lifire namelist reading
Spelling error.

2025-03-24 20:41 UTC, ekluzek commented on src/biogeochem/test/CNFireFactory_test/test_CNFireFactory.pf
> +      ! Create an exmpty namelist file for lifire namelist reading
Also remove the namelist.

2025-03-24 20:48 UTC, ekluzek commented on src/biogeochem/test/CNFireFactory_test/test_CNFireFactory.pf
> +
We think we should remove the loop over all tests, and go for the simpler standalone tests. They will only be added one at a time.

2025-03-24 20:48 UTC, ekluzek commented on src/biogeochem/test/CNFireFactory_test/test_CNFireFactory.pf
> +
Also add a test for: li2024crujra

2025-03-24 20:50 UTC, ekluzek commented on src/biogeochem/test/CNFireFactory_test/test_CNFireFactory.pf
> +
Also needs a test for fire_emis on and that it also works.

2025-03-24 20:53 UTC, ekluzek commented on src/biogeochem/test/CNFireFactory_test/test_CNFireFactory.pf
> +
Or I could add a comment about the difference between the two, as an example of two ways to do it. I think I'll check with some others about best practice here.

2025-03-24 20:55 UTC, ekluzek commented on src/biogeochem/test/CNFireFactory_test/test_CNFireFactory.pf
> +
"Repetition of the individual tests above, but turning fire-emissions on and making sure it still works."

2025-03-24 21:01 UTC, ekluzek reviewed
@slevis-lmwg and I went over this and realized some changes that should come in. Overall it's fine, but some details need to be handled.

2025-03-24 21:03 UTC, slevis-lmwg requested changes
@ekluzek and I went over and discussed various points in this PR. Erik posted our notes.

2025-03-31 07:42 UTC, ekluzek commented on bld/CLMBuildNamelist.pm
> +                           "  DON'T use the '--fire_emis' option when '--bgc sp' is activated");
On review this looks correct.

But, I see a slight tweak of wording that would be useful.

2025-03-31 07:48 UTC, ekluzek commented on src/biogeochem/test/CNFireFactory_test/test_CNFireFactory.pf
> +      ! Create an exmpty namelist file for lifire namelist reading
Resolved

2025-04-11 19:00 UTC, ekluzek commented on src/biogeochem/test/FATESFireFactory_test/test_FATESFireFactory.pf
> +            cycle
Actually doesn't need special handling. It works correctly with it.

2025-04-14 17:17 UTC, ekluzek commented on bld/CLMBuildNamelist.pm
> +          $log->fatal_error("Fire emission option $var can NOT be on BGC SP Satellite Phenology.\n" .
```suggestion
          $log->fatal_error("Fire emission option $var can NOT be on with BGC SP Satellite Phenology.\n" .
```

2025-04-14 18:32 UTC, wwieder approved these changes

2025-04-21 21:53 UTC, ekluzek commented
Error caught on Izumi for initialization with:

SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Fates.izumi_nag.clm-FatesPRISM--clm-NEON-FATES-YELL.GC.ctsm5341acl_nag

This is partially due to what I point out in #3078 

```
 (t_initf)       profile_papi_enable=      F
Runtime Error: /fs/cgd/data0/erik/ctsm_worktree/quickfix/src/biogeochem/CNVegetationFacade.F90, line 1019: ALLOCATABLE variable is not currently allocated
Program terminated by fatal error
/fs/cgd/data0/erik/ctsm_worktree/quickfix/src/biogeochem/CNVegetationFacade.F90, line 1019: Error occurred in CNVEGETATIONFACADE:ECOSYSTEMDYNAMICSPREDRAINAGE
/fs/cgd/data0/erik/ctsm_worktree/quickfix/src/main/clm_driver.F90, line 1020: Called by CLM_DRIVER:CLM_DRV
/fs/cgd/data0/erik/ctsm_worktree/quickfix/src/cpl/nuopc/lnd_comp_nuopc.F90, line 899: Called by LND_COMP_NUOPC:MODELADVANCE
/fs/cgd/data0/erik/ctsm_worktree/quickfix/components/cmeps/cime_config/../cesm/driver/esmApp.F90, line 141: Called by ESMAPP
```

2025-04-21 22:25 UTC, ekluzek commented
The izumi tests that have the problem above are:

ERI_D_Ld20.f10_f10_mg37.I2000Clm50Fates.izumi_nag.clm-FatesCold	(RUN)		
ERI_D_Ld20.f45_f45_mg37.I2000Clm50FatesRs.izumi_nag.clm-FatesColdTwoStream	(RUN)			
ERS_D_Ld5.f10_f10_mg37.I2000Clm50Fates.izumi_nag.clm-FatesCold	(RUN)		
ERS_D_Mmpi-serial_Ld5.1x1_brazil.I2000Clm50FatesRs.izumi_nag.clm-FatesCold	(RUN)		
SMS_D_Ld5.f10_f10_mg37.I2000Clm50FatesRs.izumi_nag.clm-FatesCold	(RUN)		
SMS_D_Ld5.f45_f45_mg37.I2000Clm60Fates.izumi_nag.clm-FatesCold	(RUN)		
SMS_D_Mmpi-serial_Ld5.5x5_amazon.I2000Clm60FatesCrujraRs.izumi_nag.clm-FatesCold	(RUN)		
SMS_D_Mmpi-serial_Ld5.5x5_amazon.I2000Clm60FatesRs.izumi_nag.clm-FatesCold	(RUN)

There were some build fails, that I've been successful with just resending the build with:

ERP_D_Ld5_P48x1.f10_f10_mg37.I1850Clm50Bgc.izumi_nag.clm-ciso	(SHAREDLIB_BUILD)		
ERP_D_Ld5_P48x1.f10_f10_mg37.I1850Clm60Bgc.izumi_nag.clm-ciso	(SHAREDLIB_BUILD)		
ERP_D_Ld5_P48x1.f10_f10_mg37.I1850Clm60Bgc.izumi_nag.clm-ciso--clm-matrixcnOn	(SHAREDLIB_BUILD)		
ERP_D_Ld5_P48x1.f10_f10_mg37.I2000Clm50BgcCru.izumi_nag.clm-flexCN_FUN	(SHAREDLIB_BUILD)		
ERP_D_Ld5_P48x1.f10_f10_mg37.I2000Clm50BgcCru.izumi_nag.clm-flexCN_FUN--clm-matrixcnOn	(SHAREDLIB_BUILD)		
ERP_D_Ld5_P48x1.f10_f10_mg37.I2000Clm50BgcCru.izumi_nag.clm-flexCN_FUN_BNF	(SHAREDLIB_BUILD)		
ERP_D_Ld5_P48x1.f10_f10_mg37.I2000Clm50BgcCru.izumi_nag.clm-luna	(SHAREDLIB_BUILD)		
ERP_D_Ld5_P48x1.f10_f10_mg37.I2000Clm50BgcCru.izumi_nag.clm-noFUN_flexCN	(SHAREDLIB_BUILD)		
ERP_D_Ld5_P48x1.f10_f10_mg37.I2000Clm50BgcCru.izumi_nag.clm-noFUN_flexCN--clm-matrixcnOn	(SHAREDLIB_BUILD)		
ERP_D_Ld5_P48x1.f10_f10_mg37.I2000Clm50BgcCru.izumi_nag.clm-reduceOutput	(SHAREDLIB_BUILD)		
ERP_D_Ld5_P48x1.f10_f10_mg37.I2000Clm50Sp.izumi_nag.clm-o3lombardozzi2015	(SHAREDLIB_BUILD NLCOMP)		
ERP_D_Ld9.f10_f10_mg37.I1850Clm60BgcCrop.izumi_nag.clm-clm60cam7LndTuningModeLDust	(SHAREDLIB_BUILD)		
ERP_D_P48x1.f10_f10_mg37.IHistClm60Bgc.izumi_nag.clm-decStart	(SHAREDLIB_BUILD)		
ERP_D_P48x1.f10_f10_mg37.IHistClm60Bgc.izumi_nag.clm-decStart--clm-matrixcnOn_ignore_warnings	(SHAREDLIB_BUILD)

2025-06-14 23:31 UTC, ekluzek commented
Tests are now all passing as expected.

So I'll merge this to the branch, and that merge will take care of this.

2025-06-14 23:32 UTC, merged